### ISSUE TITLE
rootpy and ROOT 6.18

### ISSUE THREAD

**Issue by rmanzoni** [rootpy/rootpy#811]
Hi!
I have recently moved to ROOT 6.18/04 and rootpy has stopped working, returning the following error at import time

```
In [2]: import rootpy
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-2-75756a455cd2> in <module>()
----> 1 import rootpy

/Users/manzoni/opt/anaconda2/lib/python2.7/site-packages/rootpy/__init__.py in <module>()
     29 from .logger import log
     30 # Needed for "from rootpy import QROOT" by other modules
---> 31 from .utils import quickroot as QROOT
     32 from . import defaults
     33 from .base import Object

/Users/manzoni/opt/anaconda2/lib/python2.7/site-packages/rootpy/utils/quickroot.py in <module>()
     13
     14
---> 15 root_module = ROOT.module._root
     16 if hasattr(root_module, 'LookupCppEntity'):  # pragma: no cover
     17     lookup_func = 'LookupCppEntity'

AttributeError: 'module' object has no attribute '_root'
```

has something changed under ROOT's hood that makes rootpy crash?

Thanks

**Comment by mrodozov** [comment]
I was reading the existing issues and I think what you have is similar to my issue which you can read about here: https://github.com/cms-sw/cmsdist/pull/5531#issuecomment-590374644
in short you are probably building (installing) the newer pyroot libs instead of the old one. If you list your ROOTSYS/lib and there is not libPyROOT but libROOTTPython that is it

**Comment by rmanzoni** [comment]
Hi @mrodozov, 

thanks for the tip.

I bumped into this problem when building ROOT from source indeed (new laptop, I wanted a fresh install), then I decided to take a different approach and install ROOT via conda and encapsulate it in a conda environment.

For the posterity, this worked with root 6.18.00

```
conda create -n alt_root python=3.7 root -c conda-forge
conda activate alt_root
conda config --env --add channels conda-forge
conda install -n alt_root root_numpy
conda install -n alt_root tensorflow -c conda-forge
conda install -n alt_root keras -c conda-forge
conda install -n alt_root matplotlib
conda install -n alt_root scikit-learn
python -m pip install rootpy --user
```

**Comment by zodiacfireworks** [comment]
Same issue here!

rootpy 1.0.1
ROOT 6.21/01

I have libROOTTPython, not libPyROOT :(

![image](https://user-images.githubusercontent.com/4976355/75581762-285be180-5a38-11ea-84f8-02c9dffb32a2.png)

Any plan to update? 
How I can help?

:)

**Comment by mrodozov** [comment]
@zodiacfireworks 
yes, that's because ROOT is moving on to new PyROOT for which they have enable building the new libs by default. You can see this comment from ROOT devs 
https://github.com/cms-sw/cmsdist/pull/5531#issuecomment-590760532
on what has changed. You can also add this cmake flag:
`-Dpyroot_experimental=OFF`
to have the old lib version

**Comment by smuzaffar** [comment]
although you can disable the new pyroot by using `-Dpyroot_experimental=OFF` but we would like to move forward with new pyroot and would like to get a version fo rootpy which works with it. Any plans  to support the new pyroot? Otherwise I am afraid we have to drop rootpy from CMSSW software stack
