### ISSUE TITLE
rootpy no fully compatible with python 2.6 on lxplus

### ISSUE THREAD

**Issue by cbourjau** [rootpy/rootpy#694]
Hello,
I am trying to run rootpy on lxplus. I followed the guide on the rootpy homepage (http://www.rootpy.org/start.html#try-rootpy-on-cern-s-lxplus) to set up my environment. However, it appears that rootpy uses subprocess.check_output which is not available in python 2.6 (and python2.6 is lxplus' standard). 

Steps to reproduce:
---------------------------
- Follow the steps at http://www.rootpy.org/start.html#try-rootpy-on-cern-s-lxplus
- Do:
```bash
$ python
Python 2.6.6 (r266:84292, Jul 23 2015, 00:03:09) 
[GCC 4.4.7 20120313 (Red Hat 4.4.7-11)] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import rootpy
>>> from rootpy import ROOT
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/afs/cern.ch/user/c/cbourjau/virtualenvs/testrootpy/lib/python2.6/site-packages/rootpy/ROOT.py", line 57, in <module>
    from . import QROOT, stl
  File "/afs/cern.ch/user/c/cbourjau/virtualenvs/testrootpy/lib/python2.6/site-packages/rootpy/stl.py", line 84, in <module>
    from . import compiled
  File "/afs/cern.ch/user/c/cbourjau/virtualenvs/testrootpy/lib/python2.6/site-packages/rootpy/compiled.py", line 52, in <module>
    from subprocess import check_output, CalledProcessError
ImportError: cannot import name check_output
```
As you can see, the problem is the usage of check_output(). Is python2.6 still officially supported? It would be great if thats the case, since it is the default on lxplus. If so, I noticed that Travis CI does not run any python2.6 tests, which would have probably spotted this.

Thanks again for this fantastic package! 
Cheers,
Christian

**Comment by ndawe** [comment]
Hi Christian,

Thanks for reporting this. Indeed it's an oversight. I can rewrite that bit of code without the use of check_output.

**Comment by ndawe** [comment]
BTW, you can also just set up python 2.7 on lxplus. It's available on afs and cvmfs.

**Comment by cbourjau** [comment]
Yes, I tried that, but found myself in dependency hell (or i simply did something wrong): The afs root5 installations seem to not work with python 2.7. But thank you very much for looking into this issue!

**Comment by ndawe** [comment]
Should be fixed by #697

**Comment by ndawe** [comment]
Can you try the master branch?

pip install --upgrade --user https://github.com/rootpy/rootpy/zipball/master

**Comment by ndawe** [comment]
It's now working for me on lxplus with 2.6

**Comment by cbourjau** [comment]
Thanks, it works splendidly indeed!

**Comment by ndawe** [comment]
Great to hear! Thanks
